export const tasks = [
  {
    id: 1,
    name: "Add form validation",
    descripiton: "Add validations to different form fields",
    priority: "medium",
    status: "backlog",
    deadline: "23/12/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 2,
    name: "Add Signup Page",
    descripiton: "Add a signup page so that users can register to our service",
    priority: "high",
    status: "backlog",
    deadline: "23/02/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 3,
    name: "Add Login Page",
    descripiton: "Add a login page and implement authorization",
    priority: "high",
    status: "backlog",
    deadline: "12/05/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 4,
    name: "Add Profile Management",
    descripiton: "Allow users to manage their user account",
    priority: "low",
    status: "backlog",
    deadline: "15/10/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 5,
    name: "Add About Page",
    descripiton: "Add About Page with a description of who built this app",
    priority: "low",
    status: "backlog",
    deadline: "18/06/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 6,
    name: "Add Proptypes",
    descripiton: "Add prop types to ensure prop type integrity",
    priority: "medium",
    status: "backlog",
    deadline: "01/06/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 7,
    name: "Ensure Code Quality",
    descripiton:
      "Make sure all code is upto standards: in use state, functional components",
    priority: "medium",
    status: "backlog",
    deadline: "04/12/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 8,
    name: "Add Services",
    descripiton: "Add Integration with the backend",
    priority: "high",
    status: "in-progress",
    deadline: "08/12/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 9,
    name: "Add Add/Edit Task",
    descripiton: "Add task creation and editing functionality",
    priority: "high",
    status: "todo",
    deadline: "17/05/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 10,
    name: "More people in one board",
    descripiton: "Add options on how to add more people on one board",
    priority: "low",
    status: "completed",
    deadline: "03/11/2022",
    board_id: 1,
    created_by: 1,
  },
  {
    id: 11,
    name: "Test Task 1 for Productivity Journal",
    descripiton: "Test Description",
    priority: "high",
    status: "backlog",
    deadline: "03/11/2022",
    board_id: 2,
    created_by: 1,
  },
  {
    id: 12,
    name: "Test Task 2 for Productivity Journal",
    descripiton: "Test Description",
    priority: "medium",
    status: "todo",
    deadline: "03/11/2022",
    board_id: 2,
    created_by: 1,
  },
  {
    id: 13,
    name: "Test Task Test 1 Board",
    descripiton: "Test",
    priority: "low",
    status: "in-progress",
    deadline: "03/11/2022",
    board_id: 3,
    created_by: 1,
  },
  {
    id: 14,
    name: "Board 3 - Task 1",
    descripiton: "Test",
    priority: "low",
    status: "backlog",
    deadline: "03/11/2022",
    board_id: 5,
    created_by: 1,
  },
  {
    id: 15,
    name: "Board 3 - Task 2",
    descripiton: "Test",
    priority: "high",
    status: "completed",
    deadline: "03/11/2022",
    board_id: 5,
    created_by: 1,
  },
];
